remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
index: index.md
defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      author_profile: false
      sidebar:
        nav: false
