remote_theme: mmistakes/minimal-mistakes
title: "Explicit or Not?"
subtitle: "A Spotify Audio Analysis"
name: "Canyon Crutchfield & Nate McNeill"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      author_profile: false
